name: restaurante
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  cloud_firestore: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/beach.png
    - assets/umbrella.png
    - assets/island.png
    - assets/beach-volleyball.png
    - assets/beach-chair.png
    - assets/hammock.png
    - assets/moai.png
    - assets/jeju.png
    - assets/island2.png
    - assets/beach-bar.png
    - assets/beach2.png
    - assets/sunrise.png
